booking/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('list_rooms/', views.get_avail_rooms, name='list_rooms'),
    path('cancel_booking/', views.cancel_booking, name='cancel_booking'),
    path('book_room/<int:pk>', views.book_room, name='book_room'),
    path('confirm_booking/<int:pk>', views.confirm_booking, name='confirm_booking'),
]

frontend/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home_view, name='home'),
    path('list_rooms/', views.get_avail_rooms, name='list_rooms'),
    path('dashboard/', views.user_dash, name='user_dash'),
    path('cancel_booking/', views.cancel_booking, name='cancel_booking'),
    path('book_room/<int:pk>', views.book_room, name='book_room'),
    path('confirm_booking/<int:pk>', views.confirm_booking, name='confirm_booking'),
]

hotelup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('booking/', include('booking.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import FloatField


class Room(models.Model):
    ROOM_CATEGORIES = (
        ('STD', 'Стандарт'),
        ('BSN', 'Бизнес'),
        ('LUX', 'Лукс'),
        ('ELUX', 'Ултра-лукс'),
        ('FAM', 'Фемили'),
    )

    number = models.IntegerField()
    beds = models.IntegerField()
    capacity = models.IntegerField()
    rate = models.FloatField()
    category = models.CharField(max_length=12, choices=ROOM_CATEGORIES)
    description = models.TextField(null=True)
    thumbnail = models.ImageField(upload_to="room_thumbnails", height_field=None, width_field=None, default='0.jpeg')

    def __str__(self) -> str:
        categories = dict(self.ROOM_CATEGORIES)
        return f'{self.number}. {categories.get(self.category)} - ({self.capacity}, {self.beds})'


class Booking(models.Model):

    BOOKING_STATUS = (
        ('active', 'Активна'),
        ('finished', 'Завършена'),
        ('canceled', 'Отменена'),
    )

    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    check_in = models.DateField()
    check_out = models.DateField()
    status = models.CharField(choices=BOOKING_STATUS, max_length=12)
    created_at = models.DateTimeField(auto_now_add=True)
    total_price = models.FloatField()

    def __str__(self) -> str:
        return f'Резервация #{self.pk} на стая {self.room.number} за периода от {self.check_in} до {self.check_out} [{self.status}]'

frontend/forms.py
from rooms.models import Room
from django import forms

class CheckRoomAvailableForm(forms.Form):
    check_in = forms.DateField(required=True, input_formats=['%Y-%m-%d'], widget=forms.DateInput(attrs={'type': 'date'}))
    check_out = forms.DateField(required=True, input_formats=['%Y-%m-%d'], widget=forms.DateInput(attrs={'type': 'date'}))
    room_category = forms.ChoiceField(choices=Room.ROOM_CATEGORIES)

frontend/views.py
from django.shortcuts import render


def home_view(request):
    return render(request, 'frontend/home.html', {})

templates/frontend/base.html
{% load static %}
<!DOCTYPE html>
<html lang="bg">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <meta name="description" content="" />
  <meta name="author" content="Bozhidar Yunchov" />
  <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
  <title>{% block page_title %}Home{% endblock %} | hotelUp!</title>

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
  {% block styles %}{% endblock styles %}

</head>

<body style="background-color: #FAFAFA;">
  <header>
    <!-- <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #00BCD4;"> -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand brand-text ml-lg-5" href="{% url 'list_rooms' %}">hotelUp!</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
        aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggler">        
        <ul class="navbar-nav ml-auto mr-5 mt-2 mt-lg-0">
          <li class="nav-item mr-2">
            <a class="nav-link" href="{% url 'home' %}">Начало</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'list_rooms' %}">Резервирай</a>
          </li>
          {% comment %} <li class="nav-item">
            <a class="nav-link" href="#">За нас</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Контакти</a>
          </li> {% endcomment %}
        </ul>

        {% if user.is_authenticated %}
        <div class="btn-group mr-5">
          <button type="button" class="btn btn-outline-light dropdown-toggle" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            {{ user.first_name }}
          </button>
          <div class="dropdown-menu dropdown-menu-lg-right user-dropdown-menu">
            <a class="dropdown-item" href="{% url 'user_dash' %}">Резервации</a>
            <div class="dropdown-divider"></div>
            {% if user.is_superuser %}
              <a class="dropdown-item" href="{% url 'admin:index' %}" target="_blank">Админ панел</a>
              <div class="dropdown-divider"></div>
            {% endif %}
            <a class="dropdown-item" href="{% url 'logout' %}">Изход</a>
          </div>
        </div>
        {% else %}
        <a href="{% url 'login' %}" class="btn btn-outline-light mr-5">Вход</a>
        {% endif %}
        
      </div>
    </nav>
  </header>

  <main class="my-5">
    {% block content %}
    {% endblock %}
  </main>

  <footer class="sticky-bottom">
    <!-- <div class="text-center text-white p-3" style="background-color:#00BCD4;"> -->
      <div class="text-center text-white p-3 bg-dark">
      Copyright © <a class="text-white" href="{% url 'list_rooms' %}">hotelUp!</a> {% now "Y" %}
    </div>
  </footer>

  {% block helpers %}
  {% endblock %}

  <!-- jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.0.1/src/js.cookie.min.js"></script>
  <script src="{% static 'js/navigation.js' %}"></script>

    {% block scripts %}
    {% endblock %}

</body>

</html>

templates/frontend/dash.html
{% extends 'frontend/base.html' %}

{% block page_title %}Dashboard{% endblock %}

{% block styles %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css">
{% endblock %}

{% block content %}
<div class="container">   
    <div class="row mb-5">
        <!-- Active bookings -->
        <div class="col-lg-4">
            <div class="card bg-success text-white">
                <div class="card-header h5 text-center">Активни резервации</div>
                <div class="card-body">
                    <h1 class="text-center">{% if 'active' in counts %}{{counts.active}}{% else %}0{% endif %}</h1>
                </div>
            </div>
        </div>
        <!-- Finished bookings -->
        <div class="col-lg-4">
            <div class="card bg-info text-white">
                <div class="card-header h5 text-center">Завършени резервации</div>
                <div class="card-body">
                    <h1 class="text-center">{% if 'finished' in counts %}{{counts.finished}}{% else %}0{% endif %}</h1>
                </div>
            </div>
        </div>
        <!-- Canceled bookings -->
        <div class="col-lg-4">
            <div class="card bg-danger text-white">
                <div class="card-header h5 text-center">Отменени резервации</div>
                <div class="card-body">
                    <h1 class="text-center">{% if 'canceled' in counts %}{{counts.canceled}}{% else %}0{% endif %}</h1>
                </div>
            </div>
        </div>
    </div>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'success' %}success{% elif message.tags == 'error' %}danger{% elif message.tags == 'info' %}info{% endif %} alert-dismissible mb-5 fade show" role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>        
        {% endfor %}
    {% endif %}
    <!-- bookings table -->
    <div class="row">
        <div class="col">
            <div class="row justify-content-between align-items-center px-3">
                <div class="col-12 col-lg-auto text-lg-start">
                    <h3 class="m-0">Списък с резервации</h3>
                </div>
                <div class="col-12 col-lg-auto text-center text-lg-end">
                    <a href="{% url 'list_rooms' %}" class="btn btn-outline-success btn-sm"><i class="fas fa-plus mx-1"></i> Резервирай стая</a>
                </div>
            </div>
            <div class="card p-4 mt-4">
                {%if booking_list%}
                <div class="form-inline mb-4">
                    <div class="form-group">
                    <label for="filterState" class="mr-3">Филтрирай по <b class="ml-1">Статус:</b></label>
                    <select id="filterState" class="form-control">
                        <option value="">----</option>
                    </select>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-bordered table-hover m-0" id="userBookings">
                        <thead>
                            <th>Резервация №</th>
                            <th>Регистрирана на</th>
                            <th>Стая</th>
                            <th>Период на престой</th>
                            <th>Цена</th>
                            <th>Статус</th>
                            <th>Действие</th>
                        </thead>
                        <tbody>
                            {% for book in booking_list %}
                            <tr>
                                <td>{{ book.pk }}</td>
                                <td>{{ book.created_at }}</td>
                                <td>{{ book.room.number }} - {{ book.room.category }}</td>
                                <td>{{ book.check_in }} - {{ book.check_out }}</td>
                                <td>{{ book.total_price }} BGN</td>
                                <td><span class="badge badge-pill badge-{% if book.status == 'active' %}success{% elif book.status == 'canceled' %}danger{% else %}info{% endif %}">{{ book.status }}</span></td>
                                <td><button class="btn btn-sm btn-danger btn-block delete" id="{{ book.pk }}" {% if book.status == 'canceled' or book.status == 'finished' %}disabled{% endif %}>Отмени</button></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <h2 class="text-center mt-5">Няма направени резервации.</h2>
                <p class="text-center">Разгледайте наличните стаи и направете резервация още сега!</p>
                <a href="{% url 'list_rooms' %}" class="btn btn-outline-info btn-lg mx-auto my-2">Резервирай стая</a>
                {% endif %}                
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block helpers %}

<div class="position-fixed bottom-0 right-0 p-3" style="z-index: 5; right: 0; bottom: 0;">
  <div id="msgToast" class="toast hide" role="alert" aria-live="assertive" data-autohide="false">
    <div class="toast-header">
      <strong class="mr-auto" id="msgToastTitle"></strong>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body" id="msgToastText"></div>
  </div>
</div>

<div class="modal fade" id="cofirmModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <p class="h3">
          Сигурни ли сте, че искате да отмените резервацията?
        </p>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">
          <i class="fas fa-times mr-2"></i> Затвори
        </button>
        <button type="button" name="confirm" id="confirm" class="btn btn-danger confirm">
          <i class="fas fa-check mr-2"></i> Потвърди
        </button>
      </div>
    </div>
  </div>
</div>
<input type="hidden" id="booking_id">
{% endblock %}

{% block scripts %}
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>

<script>

var pcol;

  $(document).ready(function () {
    let csrftoken = Cookies.get('csrftoken');
    let bookin_table = $("#userBookings");
    let book_id = $('#booking_id');
    let cofirmModal = $('#cofirmModal');
    let toast = $('#msgToast'),
        toast_title = $('#msgToastTitle'),
        toast_text = $('#msgToastText');

    bookin_table.DataTable({
        initComplete: function () {
            let column = pcol = this.api().columns(5);
            let select = $('#filterState')
                .appendTo( $(column.footer()).empty() )
                .on( 'change', function () {
                    var val = $.fn.dataTable.util.escapeRegex(
                        $(this).val()
                    );

                    column
                        .search( val ? '^'+val+'$' : '', true, false )
                        .draw();
                });

            let ar = []

            column.data()[0].forEach( function ( d, j ) {
                ar.push(d.replace(/(<([^>]+)>)/ig,""));
            } );

            let unique = [ ... new Set(ar)].sort();

            unique.forEach( function ( tag, j ) {
                select.append(`<option value="${tag}">${tag}</option>`);
            });

            delete ar;
            delete unique;
            
        }
    });

    bookin_table.on('click', '.delete', function () {
      cofirmModal.modal('show');
      book_id.val($(this).attr("id"));
    });

    cofirmModal.on('click', '.confirm', function (event) {
      event.preventDefault();
      let booking_id = book_id.val();
      $('#confirm').attr('disabled', 'disabled');
      $.ajax({
        url: "{% url 'cancel_booking' %}",
        headers: { 'X-CSRFToken': csrftoken },
        method: "POST",
        data: { 'booking_id': booking_id },
        success: function (data) {
          cofirmModal.modal('hide');
          $('#confirm').attr('disabled', false);
          //book_id.val('');
          if(data.status == 200){
              setTimeout(() => window.location.reload(), 3000);
              toast_title.text('Success');
            //window.location.reload();
          }
          else if(data.status == 401 || data.status == 404){
              toast_title.text('Error');
          }
          toast_text.text(data.msg);
            toast.toast('show');
          console.log(data);
        },
      });
    });

  });

</script>
{% endblock scripts %}

templates/frontend/home.html
{% load static %}
<!DOCTYPE html>
<html lang="bg">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="Bozhidar Yunchov" />
  <title>СВ. ИВАН РИЛСКИ</title>
  <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
  <!-- Font Awesome icons (free version)-->
  <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet" />
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

<body id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href="#page-top">СВ. ИВАН РИЛСКИ</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
        aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item"><a class="nav-link" href="#about">За нас</a></li>
          <li class="nav-item"><a class="nav-link" href="#services">Услуги</a></li>
          <li class="nav-item"><a class="nav-link" href="#contacts">Контакти</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'list_rooms' %}">Резервирай</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Master head -->
  <header class="masthead">
    <div class="container px-4 px-lg-5 d-flex flex-row h-100 align-items-center justify-content-center">
      <div class="row w-100">
        <div class="col-lg-5">
          <div class="card p-3">
            <!-- <div class="card-header">Резервирай онлайн</div> -->
            <div class="card-body">
              <h4 class="card-title mb-4 text-uppercase">Резервирай онлайн</h4>
              <!-- <p class="card-text">Отдай се на заслужен релакс</p> -->
              <form method="GET" action="{% url 'list_rooms' %}">
                <div class="form-group mb-3">
                  <label for="id_check_in" class="mb-2">Дата на настаняване</label>
                  <input type="date" class="form-control" id="id_check_in" name="checkin" required>
                </div>
                <div class="form-group mb-3">
                  <label for="id_check_out" class="mb-2">Дата на напускане</label>
                  <input type="date" class="form-control" id="id_check_out" name="checkout" required>
                </div>
                <div class="form-group mb-3">
                  <label for="id_guest_count" class="mb-2">Брой гости</label>
                  <input type="number" min="1" max="15" class="form-control" id="id_guest_count" name="capacity" value="1">
                </div>
                <button class="btn btn-primary mt-2" type="submit">Намери стая</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- About-->
  <section class="about-section bg-dark" id="about">
    <div class="container px-4 px-lg-5">
      <!-- Featured Project Row-->
      <div class="row gx-0 align-items-center">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-lg-8">
            <h2 class="text-white mb-4">ИНФОРМАЦИЯ</h2>
            <hr class="my-4 w-25 text-white" style="height:3px;" />
            <p class="text-white-50 mb-0">
              СПА Ризорт Св. Иван Рилски се намира в най-известния български ски курорт - Банско, само на 160 км. от
              София. Сгушен в прегръдките на планината и само на 10 минути от ски лифта, комплексът се състои от хотел
              със
              113 стаи, СПА Център с площ от над 1 000 кв.м. и 4 апартаментни къщи със 162 апартамента (хотелско
              настаняване се предлага в 80 от тях). Архитектурата е в типичния алпийски стил, съчетан с модерен интериор
              от дърво, камък и много светлина.
            </p>
            <p class="text-white-50 mt-4 mb-0">
              Изцяло реновиран през 2021 г., хотелът предлага целогодишна All-Inclusive програма, модерна база и голямо
              разнообразие от услуги – СПА Център на две нива с екслузивна зона за възрастни, отопляем акватоничен
              басейн
              и джакузи, външен отопляем акватоничен басейн и джакузи, съвременно оборудвана фитнес зала, ресторант с
              панорамна тераса, лоби бар, лаундж зона, детски кът, конферентни зали, магазин, ски гардероб и др.
            </p>
            <p class="text-white-50 mt-4 mb-0">
              Простиращ се на площ от 16 000 кв.м., целогодишният СПА Ризорт Св. Иван Рилски е охраняем комплекс от
              затворен тип и разполага с вътрешен двор с детска площадка, закрит паркинг и безплатен Wi-Fi на цялата си
              територия.
            </p>
          </div>
        </div>
      </div>
  </section>
  <!-- Services -->
  <section class="services-section bg-light" id="services">
    <div class="container px-4 px-lg-5">
      <h2 class="text-black text-uppercase mb-4">Услуги</h2>
      <hr class="mt-4 mb-5 text-black" style="height:3px;width:15%;">
      <!-- Service 1 Row-->
      <div class="row gx-0 mb-5 mb-lg-0 justify-content-center">
        <div class="col-lg-6"><img class="img-fluid" src="{% static 'assets/img/bg-rest-1.jpg' %}"
            alt="РЕСТОРАНТ CHEF'S KITCHEN" />
        </div>
        <div class="col-lg-6">
          <div class="bg-black text-center h-100 project">
            <div class="d-flex h-100">
              <div class="project-text w-100 my-auto text-center text-lg-left">
                <h4 class="text-white text-uppercase">РЕСТОРАНТ CHEF'S KITCHEN</h4>
                <hr class="my-3 w-25 mx-auto text-white" style="height:3px;" />
                <p class="mb-0 text-white-50">
                  Светъл и просторен, ресторантът разполага със 180 места в уютен интериор, както и тераса,
                  разкриваща панорамни гледки към Рила, Пирин и красивите пейзажи наоколо.
                </p>
                <hr class="d-none d-lg-block mb-0 ms-0" />
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Service 2 Row -->
      <div class="row gx-0 justify-content-center">
        <div class="col-lg-6"><img class="img-fluid" src="{% static 'assets/img/bg-spa-1.jpg' %}" alt="СПА Harmony" />
        </div>
        <div class="col-lg-6 order-lg-first">
          <div class="bg-black text-center h-100 project">
            <div class="d-flex h-100">
              <div class="project-text w-100 my-auto text-center text-lg-right">
                <h4 class="text-white text-uppercase">СПА “Harmony”</h4>
                <hr class="my-3 w-25 mx-auto text-white" style="height:3px;" />
                <p class="mb-0 text-white-50">
                  Вашето спокойствие е гарантирано в ръцете и грижите на СПА екипът на “Harmony”.
                  Високото ниво на професионализъм и внедрените строги хигиенни стандарти гарантират Вашето незабравимо
                  изживяване.
                </p>
                <hr class="d-none d-lg-block mb-0 me-0" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Contacts -->
  <section class="contact-section bg-black p-0" id="contacts">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5">
        <div class="col-md-10 col-lg-8 my-5">
          <h2 class="text-white text-uppercase">Контакти</h2>
          <hr class="my-4 w-25 text-white" style="height:3px;" />
        </div>
      </div>
      <div class="row gx-4 gx-lg-5">

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fas fa-map-marked-alt fa-2x text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">Адрес</h4>
              <hr class="my-4 mx-auto" />
              <div class="small text-black-50">ул. "Шинова ела" 18, Банско, България</div>
            </div>
          </div>
        </div>
        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fas fa-envelope fa-2x text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">E-mail</h4>
              <hr class="my-4 mx-auto" />
              <div class="small text-black-50"><a
                  href="mailto:reservations@saintivanrilski.com">reservations@saintivanrilski.com</a></div>
            </div>
          </div>
        </div>
        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fas fa-mobile-alt fa-2x text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">Телефон</h4>
              <hr class="my-4 mx-auto" />
              <a class="small text-black-50" href="tel:+359884991999">+359 884 991 999</a>
            </div>
          </div>
        </div>
      </div>
      <div class="social d-flex justify-content-center">
        <a class="mx-2" href="#!"><i class="fab fa-twitter"></i></a>
        <a class="mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
        <a class="mx-2" href="#!"><i class="fab fa-github"></i></a>
      </div>
    </div>
  </section>
  <!-- Footer-->
  <footer class="footer bg-black small text-center text-white-50">
    <div class="container px-4 px-lg-5">Copyright &copy; Your Website {% now "Y" %}</div>
  </footer>
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
  <script src="{% static 'js/scripts.js' %}"></script>
  <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>

</html>